# Generated by Django 3.2 on 2023-10-18 14:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_delete_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Разрешены значения от 1 до 100'), django.core.validators.MaxValueValidator(10000, 'Разрешены значения от 1 до 100')], verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to='products.product', verbose_name='Продукт в корзине')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts', to=settings.AUTH_USER_MODEL, verbose_name='Добавил в корзину')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата оформления')),
                ('status', models.CharField(choices=[(1, 'Оформлен'), (2, 'В обработке'), (3, 'Комплектуется'), (4, 'Собран'), (5, 'Передан в доставку'), (6, 'Доставлен'), (7, 'Завершен')], default=1, max_length=50)),
                ('payment_method', models.CharField(choices=[(1, 'Наличные'), (2, 'Картой на сайте'), (3, 'При получении')], default=2, max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, max_length=400)),
                ('delivery_method', models.CharField(choices=[(1, 'Пункт выдачи'), (2, 'Курьером')], default=2, max_length=50)),
                ('discount', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.shoppingcart', verbose_name='Покупки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_shopping_cart'),
        ),
    ]
